Traceback (most recent call last):
  File "/Users/isaacflath/opt/miniconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/isaacflath/opt/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/isaacflath/opt/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/isaacflath/opt/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/isaacflath/opt/miniconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/isaacflath/opt/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/isaacflath/opt/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/isaacflath/opt/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
        # Downsampling
        in_features = 64
        out_features = in_features*2
        for _ in range(2):
            model += [  nn.Conv2d(in_features, out_features, 3, stride=2, padding=1),
                        nn.InstanceNorm2d(out_features),
                        nn.ReLU(inplace=True) ]
            in_features = out_features
            out_features = in_features*2
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [6][0m, in [0;36m<cell line: 4>[0;34m()[0m
[1;32m      3[0m out_features [38;5;241m=[39m in_features[38;5;241m*[39m[38;5;241m2[39m
[1;32m      4[0m [38;5;28;01mfor[39;00m _ [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;241m2[39m):
[0;32m----> 5[0m     model [38;5;241m+[39m[38;5;241m=[39m [  nn[38;5;241m.[39mConv2d(in_features, out_features, [38;5;241m3[39m, stride[38;5;241m=[39m[38;5;241m2[39m, padding[38;5;241m=[39m[38;5;241m1[39m),
[1;32m      6[0m                 nn[38;5;241m.[39mInstanceNorm2d(out_features),
[1;32m      7[0m                 nn[38;5;241m.[39mReLU(inplace[38;5;241m=[39m[38;5;28;01mTrue[39;00m) ]
[1;32m      8[0m     in_features [38;5;241m=[39m out_features
[1;32m      9[0m     out_features [38;5;241m=[39m in_features[38;5;241m*[39m[38;5;241m2[39m

[0;31mNameError[0m: name 'model' is not defined
NameError: name 'model' is not defined

